import { Link } from 'react-router-dom';
import type { CSSProperties } from 'react';
import { aboutText, specializationText } from '../data/products';
import { ArrowRight, ShieldIcon, GridIcon, TruckIcon } from '../components/Icons';

export default function About(){return <div>
 <section className="page-hero page-hero-color"><div className="site-container"><div className="eyebrow">ABOUT AMBE MARKETING</div><h1>Quality products. Dependable service. Complete sourcing.</h1><p>AMBE MARKETING supplies IT, Power Backup and Security Solutions from leading national and international brands.</p></div></section>
 <section className="section about-page-main"><div className="site-container about-page-grid"><div className="about-page-copy"><div className="eyebrow">WHO WE ARE</div><h2>A trusted supplier and distributor for everyday technology requirements.</h2><p>{aboutText}</p><p>Registered on the Government e-Marketplace (GeM), AMBE MARKETING serves businesses, institutions, government organizations and other customers with genuine products, competitive pricing, reliable sourcing and timely delivery.</p><Link to="/products" className="button button-primary">Explore Products <ArrowRight/></Link></div><div className="about-page-visual"><img src="/assets/about-office-hq.jpg" alt="Modern professional workspace"/><div className="visual-chip"><ShieldIcon/><span><b>Trusted sourcing</b><small>IT · Power · Security</small></span></div></div></div></section>
 <section className="section section-tint"><div className="site-container"><div className="section-heading centered"><div className="eyebrow">OUR SPECIALIZATION</div><h2>Three core solution areas</h2><p>Focused supply across the categories businesses and institutions depend on.</p></div><div className="special-grid"><article style={{'--accent':'#1556c0'} as CSSProperties}><div className="special-icon"><GridIcon/></div><span>01</span><h3>IT Products & Solutions</h3><p>{specializationText.it}</p></article><article style={{'--accent':'#16854a'} as CSSProperties}><div className="special-icon"><ShieldIcon/></div><span>02</span><h3>UPS & Power Backup Solutions</h3><p>{specializationText.power}</p></article><article style={{'--accent':'#d9232e'} as CSSProperties}><div className="special-icon"><TruckIcon/></div><span>03</span><h3>Security & Surveillance Solutions</h3><p>{specializationText.security}</p></article></div></div></section>
 <section className="section objective-section"><div className="site-container objective-grid"><div className="objective-visual"><img src="/assets/products-v2/peoplelink.jpg" alt="Technology and collaboration equipment"/></div><div className="objective-copy"><div className="eyebrow">OUR OBJECTIVE</div><h2>Quality products and dependable service under one roof.</h2><p>Our objective is to provide quality products, dependable service, and complete sourcing solutions under one roof.</p><div className="mini-points"><span>Genuine products</span><span>Reliable sourcing</span><span>Timely delivery</span></div></div></div></section>
 </div>}
